### ISSUE TITLE
HTMLElement is not defined - on babel compile

### ISSUE THREAD

**Issue by kristianmandrup** [github/babel-plugin-transform-custom-element-classes#5]
ReferenceError: HTMLElement is not defined

```bash
$ npm run dev

> ce-cycle@0.0.1 dev /Users/kristianmandrup/repos/cycle-apps/ce-cycle
> cross-env NODE_ENV=development babel-node .

[dev]
/Users/kristianmandrup/repos/cycle-apps/ce-cycle/src/js/other-elem.js:1
(function (exports, require, module, __filename, __dirname) { 'use strict';Object.defineProperty(exports,"__esModule",{value:true});function _classCallCheck(instance,Constructor){if(!(instance instanceof Constructor)){throw new TypeError("Cannot call a class as a function");}}function _possibleConstructorReturn(self,call){if(!self){throw new ReferenceError("this hasn't been initialised - super() hasn't been called");}return call&&(typeof call==="object"||typeof call==="function")?call:self;}function _inherits(subClass,superClass){if(typeof superClass!=="function"&&superClass!==null){throw new TypeError("Super expression must either be null or a function, not "+typeof superClass);}subClass.prototype=Object.create(superClass&&superClass.prototype,{constructor:{value:subClass,enumerable:false,writable:true,configurable:true}});if(superClass)Object.setPrototypeOf?Object.setPrototypeOf(subClass,superClass):subClass.__proto__=superClass;}func

ReferenceError: HTMLElement is not defined
    at Object.<anonymous> (/Users/kristianmandrup/repos/cycle-apps/ce-cycle/src/js/other-elem.js:1:1028)
```

`.babelrc` file

```json
{
	"presets": ["stage-0", "es2015"],
	"plugins": [
		"transform-custom-element-classes",
		"transform-es2015-classes"
	]
}
```

Babel modules loader config:

```js
{
	test: /\.js$/,
	loader: 'babel-loader',
	exclude: /node_modules/
}
```

Any ideas? What am I missing in order for it to be "declared"?

**Comment by kristianmandrup** [comment]
I found a similar issue [here](https://github.com/ceolter/ag-grid-react/issues/24) with a hack solution...

`var HTMLElement = typeof HTMLElement === 'undefined' ? function () {} : HTMLElement;`

Now I get:

```
[dev]
/Users/kristianmandrup/repos/cycle-apps/ce-cycle/src/js/my-elem.js:1
(function (exports, require, module, __filename, __dirname) { 'use strict';Object.defineProperty(exports,"__esModule",{value:true});var _createClass=function(){function defineProperties(target,props){for(var i=0;i<props.length;i++){var descriptor=props[i];descriptor.enumerable=descriptor.enumerable||false;descriptor.configurable=true;if("value"in descriptor)descriptor.writable=true;Object.defineProperty(target,descriptor.key,descriptor);}}return function(Constructor,protoProps,staticProps){if(protoProps)defineProperties(Constructor.prototype,protoProps);if(staticProps)defineProperties(Constructor,staticProps);return Constructor;};}();function _classCallCheck(instance,Constructor){if(!(instance instanceof Constructor)){throw new TypeError("Cannot call a class as a function");}}function _possibleConstructorReturn(self,call){if(!self){throw new ReferenceError("this hasn't been initialised - super() hasn't been called");}return call&&(typeof c

TypeError: Cannot read property 'prototype' of undefined
    at Object.<anonymous> (/Users/kristianmandrup/repos/cycle-apps/ce-cycle/src/js/my-elem.js:1:1549)

npm ERR! Darwin 16.4.0
npm ERR! argv "/usr/local/bin/node" "/usr/local/bin/npm" "run" "dev"
npm ERR! node v7.7.3
npm ERR! npm  v4.1.2
```

Oddly, it worked for a while and suddenly, BOOM!!

**Comment by kristianmandrup** [comment]
`package.json`

```
  "devDependencies": {
    "babel-core": "^6.8.0",
    "babel-loader": "^6.2.4",
    "babel-plugin-transform-custom-element-classes": "^0.1.0",
    "babel-plugin-transform-es2015-classes": "^6.23.0",
    "babel-preset-es2015": "^6.6.0",
    "babel-preset-stage-0": "^6.5.0",
    "chokidar": "^1.5.0",
    "lodash.uniq": "^4.3.0",
    "webpack": "^2.1.0-beta.7",
```

**Comment by jannesiera** [comment]
Any solution to this?

**Comment by josh** [comment]
Sounds like your set up is trying to load the custom element script in a Nodejs environment. This transform targets browsers, not node.
